# Database configuration for a Ruby on Rails application using PostgreSQL
# test
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: albumtrackca_development
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "1234") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>

test:
  <<: *default
  database: albumtrackca_test
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "1234") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

  queue:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

  cache:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
