default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST", "127.0.0.1") %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "1234") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: albumtrackca_development

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "albumtrackca_test") %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
