default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: 1234
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: albumtrackca_development

test:
  <<: *default
  database: albumtrackca_test

production:
  <<: *default
  database: albumtrackca_production
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
